# Generated by Django 5.0.7 on 2024-08-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_create_at_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobile',
        ),
    ]
